name: stockle

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    networks:
      - stockle-app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - stockle-app

networks:
  stockle-app:
    driver: bridge
